### ISSUE TITLE
time lable is wrong 

### ISSUE THREAD

**Issue by Nokius** [SfietKonstantin/harbour-twablet#24]
The information about the time of the tweet is minimum 2h but it's just a few minutes old. This happen for both streams.

**Comment by SfietKonstantin** [comment]
This happens if your tweet is a retweet. I report the timestamp or fhe original tweet.
Please check if this is what you have.

Or wait, maybe this is timezone again !

**Comment by Nokius** [comment]
No, sadly also for 'normal' tweets

**Comment by SfietKonstantin** [comment]
I have send a fix in release 0.0.18. Can you update and check if this is fixed ? :)

**Comment by Nokius** [comment]
tweetian:
![20151001232835](https://cloud.githubusercontent.com/assets/879178/10234365/5d3fad90-6894-11e5-9516-01f395509ca5.jpg)

twablet:
![home](https://cloud.githubusercontent.com/assets/879178/10234405/a5b6cc5c-6894-11e5-8187-f906cc39ceb5.jpg)

**Comment by Nokius** [comment]
fixed with 0.0.18 !

![working](https://cloud.githubusercontent.com/assets/879178/10234514/5d3df896-6895-11e5-8741-e314900a9562.jpg)

**Comment by SfietKonstantin** [comment]
Thanks ! Closing.
/me hates timezones ...
