### ISSUE TITLE
Image browser

### ISSUE THREAD

**Issue by SfietKonstantin** [SfietKonstantin/harbour-twablet#25]
We need a full-screen image browser for tweets.

**Comment by M4rtinK** [comment]
I guess this covers both being able to see full size pictures and being able to see all pictures attached to a tweet ?

Also this issue is most probably a dependency for issue #41.

**Comment by SfietKonstantin** [comment]
Seeing all pictures in a Tweet is not possible (yet?)
It is a limitation of the Twitter API.
So this only covers the picture viewer.

**Comment by M4rtinK** [comment]
> Seeing all pictures in a Tweet is not possible (yet?)

Yep, only the first pictures is shown, even if more pictures have been attached to the tweet.

**Comment by M4rtinK** [comment]
And for the record Tweetian behaves in the same way - only shows the first picture and the only way to see the others (or even check they are there) is to open the tweet in the browser.

**Comment by SfietKonstantin** [comment]
@M4rtinK let's handle the multiple images in #44
