### ISSUE TITLE
Tweets multiple times in stream

### ISSUE THREAD

**Issue by Nokius** [SfietKonstantin/harbour-twablet#43]
Not sure if this bug is related to issue #31, but sometime tweets are multiple times in the stream.

I found a way to reproduce it:
refresh and before the refresh is done trigger a refresh again. The mount of triggered refreshes you will see the tweets in the stream.

may a solution is to wait with an refresh until the last one is done to avoid this issue.

**Comment by SfietKonstantin** [comment]
Haha, interesting. Thanks for the test-case.
