### ISSUE TITLE
multiple pictures attached on tweet 

### ISSUE THREAD

**Issue by Nokius** [SfietKonstantin/harbour-twablet#44]
If a Tweet has multiple attached pictures twablet shows only the first picture not the rest.

**Comment by SfietKonstantin** [comment]
I wonder why I don't get the extended data from Twitter
https://dev.twitter.com/overview/api/entities-in-twitter-objects#extended_entities

**Comment by Nokius** [comment]
Not sure but maybe `type` is some thing u can check

**Comment by SfietKonstantin** [comment]
Closed via e1b2a58c6e93f1d2f18e254e41ab86a6486ef496

**Comment by Nokius** [comment]
in Version 0.5.9-10.44 it looks like this 
![20151008221332](https://cloud.githubusercontent.com/assets/879178/10378600/12a7e970-6e0a-11e5-8074-7bfe54d59def.jpg)

**Comment by SfietKonstantin** [comment]
Well, that's a nice bug you have here. Reopening it

**Comment by Nokius** [comment]
in the latest version (0.5.10-10.45.1) loading pictures takes a few seconds, and the canvas is empty I will check it later today in a other network (wifi atm)

**Comment by SfietKonstantin** [comment]
Do you have screenshots ? 
Can this relate to #47 ?

**Comment by Nokius** [comment]
yes may thats related to #47 

the fix for multi pictures is **smile face** thanks a lot!
