### ISSUE TITLE
Header picture not shown

### ISSUE THREAD

**Issue by Nokius** [SfietKonstantin/harbour-twablet#47]
some Profiles have no Header picture of the Account visible[the account has one].

**Comment by M4rtinK** [comment]
I can confirm also seeing this, but I haven't found any pattern yet.

Possible causes from top of my head:
- unhandled image format of some header pictures
- unhandled profile image size
- transient image download error

**Comment by SfietKonstantin** [comment]
I will vote for option 3. This relates to #16, as we cannot reload images that failed to load.

**Comment by SfietKonstantin** [comment]
@M4rtinK, @Nokius mind trying again with latest build ? I should be able to reload picture when network is up again, as well as reporting when an image just fails to load.

**Comment by Nokius** [comment]
I will test it :)

**Comment by SfietKonstantin** [comment]
Should this be closed ?

**Comment by Nokius** [comment]
it looks like it's working correct, and once I saw a ! when the header was missing

**Comment by SfietKonstantin** [comment]
Let's close this issue ATM. We can reopen if we still have issues.
