### ISSUE TITLE
old 'code' in the project 

### ISSUE THREAD

**Issue by Nokius** [SfietKonstantin/harbour-twablet#51]
after my catch from last night 86acee

I found more 'old' code, I found out that UserPage.qml shows 'friends' not followers.

> grep -r 'friends'
> src/tests/tst_tweetrepository.cpp:        user.insert(QLatin1String{"friends_count"}, 789);
> src/tests/tst_tweetrepository.cpp:        user.insert(QLatin1String{"friends_count"}, 56);
> src/bin/translations/harbour-twablet-de.ts:        <source>%1&apos;s friends</source>
> src/bin/translations/harbour-twablet-de.ts:friends</source>
> src/bin/translations/harbour-twablet-de.ts:        <source>No friends</source>
> src/bin/translations/harbour-twablet.ts:        <source>%1&apos;s friends</source>
> src/bin/translations/harbour-twablet.ts:friends</source>
> src/bin/translations/harbour-twablet.ts:        <source>No friends</source>
> src/bin/qml/pages/RightPanel.qml:            title: qsTr("%1's friends").arg(screenName),
> src/bin/qml/pages/UserPage.qml:                    text: query.user ? qsTr("%n\nfriends", "", query.user.friendsCount) : ""
> src/bin/qml/pages/UsersPage.qml:            errorMessage: (model.status === Model.Idle && model.count === 0) ? qsTr("No friends") : ""
> src/lib/query.h:         \* @ brief Query the list of friends of an user (following)
> src/lib/qml/userobject.h:    Q_PROPERTY(int friendsCount READ friendsCount CONSTANT)
> src/lib/qml/userobject.h:    int friendsCount() const;
> src/lib/qml/userobject.cpp:int UserObject::friendsCount() const
> src/lib/qml/userobject.cpp:    return m_data.friendsCount();
> src/lib/usercentralrepository.cpp:#include "friendsqueryhandler.h"
> src/lib/friendsqueryhandler.cpp:#include "friendsqueryhandler.h"
> src/lib/friendsqueryhandler.cpp:    return QLatin1String{"friends/list.json"};
> src/lib/user.cpp:    m_friendsCount = json.value(QLatin1String("friends_count")).toInt();
> src/lib/user.cpp:int User::friendsCount() const
> src/lib/user.cpp:    return m_friendsCount;
> src/lib/CMakeLists.txt:    friendsqueryhandler.cpp
> src/lib/user.h:    int friendsCount() const;
> src/lib/user.h:    int m_friendsCount {0};

Just changing the visible (to the user) Strings will may be more like a hot fix and make the project harder to maintenance.

**Comment by SfietKonstantin** [comment]
As discussed, this is related to how Twitter handles followees (people you follow).
I see some GUI strings, I will remove them, but for filenames, I will keep them, to match Twitter API.

**Comment by Nokius** [comment]
ok :)

for that I have a PR nearly ready just have to go back home :P
