### ISSUE TITLE
Clickable profile names in the main feed view

### ISSUE THREAD

**Issue by M4rtinK** [SfietKonstantin/harbour-twablet#63]
I'm not sure that having the profile names clickable in the main feed/column view is a good idea - it quite often happens that I want to click a tweet to get to the tweet detail screen but instead the header with the profile name gets clicked and I go to the profile screen for the tweet author instead. 

I think that other users might have similar issues, as I would guess people would generally want to get to the tweet detail screen much more often than to look at tweet author profiles.

So maybe the profile names should not be separately clickable but instead be part of a clickable area that shows the tweet details screen ? Then on the tweet detail screen the profile name would be normally clickable and would bring the profile screen for the author.

**Comment by SfietKonstantin** [comment]
Agreed. Let's fix this for next beta release
